tx = txsite('Name','Ground Station', ...
        'Latitude', 32.940727, ...
        'Longitude', -106.922101, 'AntennaHeight', 1.5, ...
        'SystemLoss', 10, ...
        "TransmitterFrequency", 900e6, ...
        "TransmitterPower", 10);
    
rx = rxsite('Name','Rocket', ...
       'Latitude',32.195200, ...
       'Longitude',-107.847713,'AntennaHeight',0.5,...
       'SystemLoss',10,...
       'Antenna', dipole,...
       'ReceiverSensitivity', -121);
    
pm = propagationModel('longley-rice', ...
    'GroundConductivity', 4, ...
    'ClimateZone', 'desert');

    
coverage(tx, rx, 'SignalStrengths',-121:-60,...
       'PropagationModel', pm);